### ISSUE TITLE
Add support for 3rd party fields

### ISSUE THREAD

**Issue by pagelab** [RostiMelk/ACF-Tools#1]
This is so useful, thanks for making it free. 🎉

What about adding support for fields from [some of the main ACF's extensions](https://www.awesomeacf.com/)?

**Comment by RostiMelk** [comment]
I'll have a look at this. Any fields you want me to prioritize?

**Comment by pagelab** [comment]
Yes, here's some of the most interesting IMO:

- Icon selector (Font Awesome) 
- Google font selector
- Image crop
- Navigation menu
- RGBA Color selector
- Number slider
- Post Type selector
- Code field
- Link
- Range
- Focal Point (for images)

**Comment by RostiMelk** [comment]
Alright, I'll add support for it next week. :)

Update: Sorry for the delay. As of now I am building a way for others to add 3rd party fields, so this will not get prioritized.

**Comment by RostiMelk** [comment]
Feature to add your own 3rd party fields is put on hold for now.
Opening this issue again to finally add some support for 3rd-party fields.

**Comment by RostiMelk** [comment]
v3.0.1 includes support for some of the requested third party fields.
Here is a list:
- Font Awesome (mattkeys)
- Image Aspect Ratio Crop (Johannes Siipola)
- Nav Menu Field (Faison Zutavern)
- RGBA Color Picker (Thomas Meyer )
- Code Field (Peter Tasker)

I will continue to add more support for third party fields down the road. 
Closing this issue for now.
