### ISSUE TITLE
Browser history

### ISSUE THREAD

**Issue by danielbenjamins** [RostiMelk/ACF-Tools#24]
Just wondering why I need to give the extension permission to access my browser history?

**Comment by RostiMelk** [comment]
Hi!
The extension does not gather any data of that sort.

#### These are the permissions I use and why:
**activeTab**

To inject javascript and css into the Wordpress page

**storage**
To save user settings using the native chrome storage api**

**tabs**
Simply to give the user feedback on wether the extension is running and injecting code or not. I will see if I can get rid of this and get by with using activeTab for this instead.

I can assure you that no data gets sent to me or anywhere else. Feel free to look around in the code to verify.

**Comment by RostiMelk** [comment]
Hello again!

I have just published a new release: v3.0.2
Turns out I did not need that Tabs permission, and it has now been removed. 

The release is currently live on Github and Firefox. Chrome is waiting for approval.

**Comment by danielbenjamins** [comment]
No problem, I was just wondering since it seemed a bit odd to me. Thanks for clarifying!
