### ISSUE TITLE
what are these settings for?

### ISSUE THREAD

**Issue by Nickyg001** [RostiMelk/ACF-Tools#29]
Nice Plug-in, very useful.
Could I know what those settings are for and the difference between on / off of the same? I can't find any reference in the guide.

- If statements for basic fields
- Spacing on field code -> TAB | 1stace / 8 space

![image](https://user-images.githubusercontent.com/33684734/100095520-e5aa2700-2e5a-11eb-973a-b339261d8fee.png)

**Comment by RostiMelk** [comment]
Hi!

**The first setting is to set whether you want if statements in your code output or not.** 
This setting will only affect field output for fields listed under "Basic fields" in the Field Type dropdown.

Here is an example with if statements turned OFF:
```php
<?php echo get_sub_field( 'text' ); ?>
```

And here is is turned ON:
```php
<?php if ( $text = get_sub_field( 'text' ) ) : ?>
	<?php echo $text; ?>
<?php endif; ?>
```

All code put inside the if-statements will not output if the ACF field is left blank.


**The second setting changes the indentation on the field code output**
Here is an example using "Tab"
```php
<?php if ( $text = get_sub_field( 'text' ) ) : ?>
	<?php echo $text; ?>
<?php endif; ?>
```
And here is an example using "2 spaces"
```php
<?php if ( $text = get_sub_field( 'text' ) ) : ?>
  <?php echo $text; ?>
<?php endif; ?>
```

Glad you like the extension!

**Comment by Nickyg001** [comment]
[it.zip](https://github.com/RostiMelk/ACF-Tools/files/5596938/it.zip)

yes now I understand, after I ask you some things about the use of the IF. (now I have to escape) ...

I am happy with the extension that I have translated into Italian I hope you will add it soon ...

Ps: I can manually insert the language file I made in my installation how can I [do?

**Comment by RostiMelk** [comment]
Thanks for contributing! If you don't mind, could you submit it in a pull request?
I have written some instructions on how to contribute translations here: https://github.com/RostiMelk/ACF-Tools#translation
