### ISSUE TITLE
No Sub Fields Button Recognised?  - I might be me?

### ISSUE THREAD

**Issue by digger1410** [RostiMelk/ACF-Tools#33]
Please have a look at the attached screenshot.
I cannot seem to locate the 'copy code with sub fields'?
I have flexible content but only the 'copy code' button on its own.
![Screenshot 2021-02-15 at 13 54 10](https://user-images.githubusercontent.com/79094870/107955268-7d6c6c80-6f95-11eb-99c6-738c3631ca2f.jpg)

**Comment by digger1410** [comment]
A screenshot of my screen is as follows (no sub field button?)
![Screenshot 2021-02-15 at 13 57 13](https://user-images.githubusercontent.com/79094870/107955560-d5a36e80-6f95-11eb-9d1c-f246482ae19e.jpg)

**Comment by RostiMelk** [comment]
The  'copy code with sub fields' button will only show up for group and repeater fields as of now. 
Functionality for flexible content might be developed in the future, but as of now I have limited time and resources.
